package net.agm.hydra.model;
// Generated 9-feb-2021 15.20.01 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Assigned generated by hbm2java
 */
@Entity
@Table(name = "assigned")
public class Assigned implements java.io.Serializable {

	private Long id;
	private Tasks tasks;
	private Users users;
	private Set<Updates> updateses = new HashSet<Updates>(0);

	public Assigned() {
	}

	public Assigned(Long id, Tasks tasks, Users users) {
		this.id = id;
		this.tasks = tasks;
		this.users = users;
	}

	public Assigned(Long id, Tasks tasks, Users users, Set<Updates> updateses) {
		this.id = id;
		this.tasks = tasks;
		this.users = users;
		this.updateses = updateses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
     
	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_id", nullable = false)
	public Tasks getTasks() {
		return this.tasks;
	}

	public void setTasks(Tasks tasks) {
		this.tasks = tasks;
	}
     
	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
    
	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assigned")
	public Set<Updates> getUpdateses() {
		return this.updateses;
	}

	public void setUpdateses(Set<Updates> updateses) {
		this.updateses = updateses;
	}

}
