package net.agm.hydra.model;
// Generated 19-mar-2021 16.54.53 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.ToString;

/**
 * License generated by hbm2java
 */
@Entity
@Table(name = "license")
@ToString
public class License implements java.io.Serializable {

	private Long id;
	private String email;
	private String businessName;
	private Date startDate;
	private Date endDate;
	private Float cost;
	private Float paid;
	private Set<Assigned> assigneds = new HashSet<Assigned>(0);
	private Set<Projects> projectses = new HashSet<Projects>(0);
	private Set<Tasks> taskses = new HashSet<Tasks>(0);
	private Set<Bookables> bookableses = new HashSet<Bookables>(0);
	private Set<Books> bookses = new HashSet<Books>(0);
	private Set<Roles> roleses = new HashSet<Roles>(0);
	private Set<Users> userses = new HashSet<Users>(0);

	public License() {
	}

	public License(String email, String businessName, Date startDate, Date endDate) {
		this.email = email;
		this.businessName = businessName;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public License(String email, String businessName, Date startDate, Date endDate, Float cost, Float paid,
			Set<Assigned> assigneds, Set<Projects> projectses, Set<Tasks> taskses, Set<Bookables> bookableses,
			Set<Books> bookses, Set<Roles> roleses, Set<Users> userses) {
		this.email = email;
		this.businessName = businessName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.cost = cost;
		this.paid = paid;
		this.assigneds = assigneds;
		this.projectses = projectses;
		this.taskses = taskses;
		this.bookableses = bookableses;
		this.bookses = bookses;
		this.roleses = roleses;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "business_name", nullable = false)
	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 13)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 13)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "cost", precision = 8, scale = 8)
	public Float getCost() {
		return this.cost;
	}

	public void setCost(Float cost) {
		this.cost = cost;
	}

	@Column(name = "paid", precision = 8, scale = 8)
	public Float getPaid() {
		return this.paid;
	}

	public void setPaid(Float paid) {
		this.paid = paid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "license")
	public Set<Assigned> getAssigneds() {
		return this.assigneds;
	}

	public void setAssigneds(Set<Assigned> assigneds) {
		this.assigneds = assigneds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "license")
	public Set<Projects> getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set<Projects> projectses) {
		this.projectses = projectses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "license")
	public Set<Tasks> getTaskses() {
		return this.taskses;
	}

	public void setTaskses(Set<Tasks> taskses) {
		this.taskses = taskses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "license")
	public Set<Bookables> getBookableses() {
		return this.bookableses;
	}

	public void setBookableses(Set<Bookables> bookableses) {
		this.bookableses = bookableses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "license")
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "license")
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "license")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
