package net.agm.hydra.model;
// Generated 16-mar-2021 17.41.48 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import net.agm.hydra.model.base.BaseEntity;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "projects")
public class Projects extends BaseEntity  {

	private Long id;
	private String name;
	private String description;
	private Date startDate;
	private Date endDate;
	private int totalDays;
	private String tenantId;
	private Set<Tasks> taskses = new HashSet<Tasks>(0);

	public Projects() {
	}

	public Projects(String name, Date startDate, Date endDate, int totalDays) {
		this.name = name;
		this.startDate = startDate;
		this.endDate = endDate;
		this.totalDays = totalDays;
	}

	public Projects(String name, String description, Date startDate, Date endDate, int totalDays, String tenantId,
			Set<Tasks> taskses) {
		this.name = name;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
		this.totalDays = totalDays;
		this.tenantId = tenantId;
		this.taskses = taskses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 13)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 13)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "total_days", nullable = false)
	public int getTotalDays() {
		return this.totalDays;
	}

	public void setTotalDays(int totalDays) {
		this.totalDays = totalDays;
	}

	@Column(name = "tenant_id")
	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<Tasks> getTaskses() {
		return this.taskses;
	}

	public void setTaskses(Set<Tasks> taskses) {
		this.taskses = taskses;
	}

}
