package net.agm.hydra.model;
// Generated 12-feb-2021 17.03.58 by Hibernate Tools 5.2.12.Final

import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import net.agm.hydra.datamodel.Status;

/**
 * Tasks generated by hbm2java
 */
@Entity
@Table(name = "tasks")
public class Tasks implements java.io.Serializable {

	private Long id;
	private Projects projects;
	private String taskName;
	private LocalDate dateOfRegistation;
	private Status status;
	private Double totalWorked;
	private Set<Assigned> assigneds = new HashSet<Assigned>(0);

	public Tasks() {
	}

	public Tasks(Projects projects, String taskName, LocalDate dateOfRegistation, Status status) {
		this.projects = projects;
		this.taskName = taskName;
		this.dateOfRegistation = dateOfRegistation;
		this.status = status;
	}

	public Tasks(Projects projects, String taskName, LocalDate dateOfRegistation, Status status, Double totalWorked,
			Set<Assigned> assigneds) {
		this.projects = projects;
		this.taskName = taskName;
		this.dateOfRegistation = dateOfRegistation;
		this.status = status;
		this.totalWorked = totalWorked;
		this.assigneds = assigneds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@Column(name = "task_name", nullable = false)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "date_of_registation", nullable = false, length = 13)
	public LocalDate getDateOfRegistation() {
		return this.dateOfRegistation;
	}

	public void setDateOfRegistation(LocalDate dateOfRegistation) {
		this.dateOfRegistation = dateOfRegistation;
	}

	@Column(name = "status", nullable = false, length = 20)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "total_worked", precision = 2)
	public Double getTotalWorked() {
		return this.totalWorked;
	}

	public void setTotalWorked(Double totalWorked) {
		this.totalWorked = totalWorked;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tasks")
	public Set<Assigned> getAssigneds() {
		return this.assigneds;
	}

	public void setAssigneds(Set<Assigned> assigneds) {
		this.assigneds = assigneds;
	}

}
