package net.agm.hydra.model;
// Generated 5-feb-2021 11.57.39 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Updates generated by hbm2java
 */
@Entity
@Table(name = "updates")
public class Updates implements java.io.Serializable {

	private long updateId;
	private Assigned assigned;
	private Date dateOfPublish;
	private BigDecimal hoursOfWorking;

	public Updates() {
	}

	public Updates(long updateId, Assigned assigned, Date dateOfPublish, BigDecimal hoursOfWorking) {
		this.updateId = updateId;
		this.assigned = assigned;
		this.dateOfPublish = dateOfPublish;
		this.hoursOfWorking = hoursOfWorking;
	}

	@Id

	@Column(name = "update_id", unique = true, nullable = false)
	public long getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(long updateId) {
		this.updateId = updateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assigned_id", nullable = false)
	public Assigned getAssigned() {
		return this.assigned;
	}

	public void setAssigned(Assigned assigned) {
		this.assigned = assigned;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_publish", nullable = false, length = 29)
	public Date getDateOfPublish() {
		return this.dateOfPublish;
	}

	public void setDateOfPublish(Date dateOfPublish) {
		this.dateOfPublish = dateOfPublish;
	}

	@Column(name = "hours_of_working", nullable = false, precision = 3)
	public BigDecimal getHoursOfWorking() {
		return this.hoursOfWorking;
	}

	public void setHoursOfWorking(BigDecimal hoursOfWorking) {
		this.hoursOfWorking = hoursOfWorking;
	}

}
