package net.agm.hydra.model;
// Generated 10-feb-2021 11.31.06 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Updates generated by hbm2java
 */
@Entity
@Table(name = "updates")
public class Updates implements java.io.Serializable {

	private Long id;
	private Assigned assigned;
	private LocalDateTime dateOfPublish;
	private BigDecimal hoursOfWorking;

	public Updates() {
	}

	public Updates(Long id, Assigned assigned, LocalDateTime dateOfPublish, BigDecimal hoursOfWorking) {
		this.id = id;
		this.assigned = assigned;
		this.dateOfPublish = dateOfPublish;
		this.hoursOfWorking = hoursOfWorking;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assigned_id", nullable = false)
	public Assigned getAssigned() {
		return this.assigned;
	}

	public void setAssigned(Assigned assigned) {
		this.assigned = assigned;
	}

	@Column(name = "date_of_publish", nullable = false, length = 29)
	public LocalDateTime getDateOfPublish() {
		return this.dateOfPublish;
	}

	public void setDateOfPublish(LocalDateTime dateOfPublish) {
		this.dateOfPublish = dateOfPublish;
	}

	@Column(name = "hours_of_working", nullable = false, precision = 3)
	public BigDecimal getHoursOfWorking() {
		return this.hoursOfWorking;
	}

	public void setHoursOfWorking(BigDecimal hoursOfWorking) {
		this.hoursOfWorking = hoursOfWorking;
	}

}
