package net.agm.hydra.model;
// Generated 4-feb-2021 10.50.46 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Updates generated by hbm2java
 */
@Entity
@Table(name = "updates")
public class Updates implements java.io.Serializable {

	private long taskId;
	private Tasks tasks;
	private Users users;
	private Date dateOfPublish;
	private BigDecimal hoursOfWorking;

	public Updates() {
	}

	public Updates(Tasks tasks, Users users, Date dateOfPublish, BigDecimal hoursOfWorking) {
		this.tasks = tasks;
		this.users = users;
		this.dateOfPublish = dateOfPublish;
		this.hoursOfWorking = hoursOfWorking;
	}

	@GenericGenerator(name = "net.agm.hydra.model.UpdatesIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tasks"))
	@Id
	@GeneratedValue(generator = "net.agm.hydra.model.UpdatesIdGenerator")

	@Column(name = "task_id", unique = true, nullable = false)
	public long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(long taskId) {
		this.taskId = taskId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tasks getTasks() {
		return this.tasks;
	}

	public void setTasks(Tasks tasks) {
		this.tasks = tasks;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_publish", nullable = false, length = 13)
	public Date getDateOfPublish() {
		return this.dateOfPublish;
	}

	public void setDateOfPublish(Date dateOfPublish) {
		this.dateOfPublish = dateOfPublish;
	}

	@Column(name = "hours_of_working", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getHoursOfWorking() {
		return this.hoursOfWorking;
	}

	public void setHoursOfWorking(BigDecimal hoursOfWorking) {
		this.hoursOfWorking = hoursOfWorking;
	}

}
